baseURL: "https://cleoisme.github.io/"
title: "Cleo is Me"
paginate: 5
theme: anatole

enableEmoji: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      - main:
          - name: "Home"
            identifier: "home"
            weight: 100
            url: "/"
          - name: "Experience"
            identifier: "experience"
            weight: 200
            url: "experience/"
          - name: "Projects"
            identifier: "projects"
            weight: 300
            url: "projects/"
          - name: "Education"
            identifier: "education"
            weight: 400
            url: "education/"
          - name: "Extended Learning"
            identifier: "extlearning"
            weight: 500
            url: "extlearning/"
          - name: "Certificates"
            identifier: "certificates"
            weight: 100
            url: "extlearning/certificates/"
            parent: "extlearning"
          - name: "Books"
            identifier: "books"
            weight: 200
            url: "extlearning/books/"
            parent: "extlearning"
          - name: "About"
            identifier: "about"
            weight: 600
            url: "about/"

params:
  author: "Cleo"
  description: "Call me Cleo"
  profilePicture: "images/profile.jpg"
  copyright: "2020-{{ YEAR }}"
  favicon: "favicons/"
  socialIcons:
    - icon: "fab fa-linkedin"
      title: "Linkedin"
      url: "https://www.linkedin.com/in/cleo-zhang/"
    - icon: "fab fa-github"
      title: "Github"
      url: "https://github.com/cleoisme"
    - icon: "fab fa-instagram"
      title: "Instagram"
      url: "https://instagram.com/c1eoisme?igshid=MmIzYWVlNDQ5Yg=="
    - icon: "fa fa-calendar-days"
      title: "Calendly"
      url: "https://calendly.com/cyintl"
