baseURL: "https://cleoisme.github.io/"
title: "Cleo is Me"
paginate: 5
theme: anatole

enableEmoji: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      - main:
          - name: "Home"
            identifier: "home"
            weight: 100
            url: "/"
          - name: "Experience"
            identifier: "experience"
            weight: 200
            url: "experience/"
          - name: "Projects"
            identifier: "projects"
            weight: 300
            url: "projects/"
          - name: "Education"
            identifier: "education"
            weight: 400
            url: "education/"
          - name: "Extended Learning"
            identifier: "extlearning"
            weight: 500
            url: "extlearning/"
          - name: "Certificates"
            identifier: "certificates"
            weight: 100
            url: "extlearning/certificates/"
            parent: "extlearning"
          - name: "Books"
            identifier: "books"
            weight: 200
            url: "extlearning/books/"
            parent: "extlearning"
          - name: "About"
            identifier: "about"
            weight: 600
            url: "about/"

params:
  author: "Cleo"
  description: "Call me Cleo"
  profilePicture: "images/profile.jpg"
  socialIcons:
    - icon: "fab fa-linkedin"
      title: "Linkedin"
      url: "https://de.linkedin.com/"
    - icon: "fab fa-github"
      title: "Github"
      url: "https://de.github.com/"
    - icon: "fab fa-facebook"
      title: "Facebook"
      url: "https://de.facebook.com/"
    - icon: "fab fa-instagram"
      title: "Instagram"
      url: "https://de.instagram.com/"
    - icon: "fab fa-calendly"
      title: "Calendly"
      url: "https://de.calendly.com/"
